### ISSUE TITLE
Node v18 "fetch" causes exception on LSP startup

### ISSUE THREAD

**Issue by dansalvato** [grahambates/m68k-lsp#6] opened 2022-07-11 23:20 UTC
```
[ERROR][2022-07-11 17:08:08] .../vim/lsp/rpc.lua:420	"rpc"	"m68k-lsp-server"	"stderr"	"(node:43562) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time\n(Use `node --trace-warnings ...` to show where the warning was created)\n"
[ERROR][2022-07-11 17:08:08] .../vim/lsp/rpc.lua:420	"rpc"	"m68k-lsp-server"	"stderr"	"node:internal/deps/undici/undici:4832\n            throw new TypeError(\"Failed to parse URL from \" + input, { cause: err });\n                  ^\n\nTypeError: Failed to parse URL from /opt/homebrew/lib/node_modules/m68k-lsp-server/node_modules/web-tree-sitter/tree-sitter.wasm\n    at new Request (node:internal/deps/undici/undici:4832:19)\n    at Agent.fetch2 (node:internal/deps/undici/undici:5524:29)\n    ... 4 lines matching cause stack trace ...\n    at new Promise (<anonymous>)\n    at Parser.init (/opt/homebrew/lib/node_modules/m68k-lsp-server/node_modules/web-tree-sitter/tree-sitter.js:1:332)\n    at $l (/opt/homebrew/lib/node_modules/m68k-lsp-server/out/server.js:300:2915)\n    at /opt/homebrew/lib/node_modules/m68k-lsp-server/out/server.js:300:3197 {\n  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL\n      at new NodeError (node:internal/errors:388:5)\n      at URL.onParseError (node:internal/url:564:9)\n      at new URL (node:internal/url:644:5)\n      at new Request (node:internal/deps/undici/undici:4830:25)\n      at Agent.fetch2 (node:internal/deps/undici/undici:5524:29)\n      at Object.fetch (node:internal/deps/undici/undici:6351:20)\n      at fetch (node:internal/bootstrap/pre_execution:197:25)\n      at /opt/homebrew/lib/node_modules/m68k-lsp-server/node_modules/web-tree-sitter/tree-sitter.js:1:15192\n      at /opt/homebrew/lib/node_modules/m68k-lsp-server/node_modules/web-tree-sitter/tree-sitter.js:1:15413\n      at new Promise (<anonymous>) {\n    input: '/opt/homebrew/lib/node_modules/m68k-lsp-server/node_modules/web-tree-sitter/tree-sitter.wasm',\n    code: 'ERR_INVALID_URL'\n  }\n}\n\nNode.js v18.5.0\n"
```

Seems to be the same issue as referenced here: https://github.com/emscripten-core/emscripten/issues/16913

I was able to workaround by adjusting the first line of `m68k-lsp-server` (the npm package) to include the `--no-experimental-fetch` argument:

```js
#!/usr/bin/env node --no-experimental-fetch
require("./out/server");
```

Maybe building with an updated emscripten would fix this (it seems like the issue was addressed on their side), but otherwise it seems my workaround works perfectly fine as well.

**Comment by grahambates** [comment] 2022-07-12 12:10
Annoyingly that quick fix results in an error on node <=15: `node: bad option: --no-experimental-fetch`. We really need to support node 14 given in's still in LTS.

I'll try the updated emscripten.

**Comment by grahambates** [comment] 2022-07-12 16:53
This appears to have fixed it. Let me know if it's resolved the issue for you too.

**Comment by docbobo** [comment] 2022-08-05 09:58
Apologies for chiming in on something that's already marked as closed. 

I started looking into this language server yesterday and had the exact same problem as described here. In my case, something similar to what has been suggested above worked:

```
#!/usr/bin/env -S node --no-experimental-fetch
```

I am on node v18.7.0 and since I've only installed this yesterday should be running v0.8.0. I've also compared that my local vasmm68k_mot has the changes from the commit above.

**Comment by grahambates** [comment] 2022-08-05 10:12
Ok that's strange, it looked to me like the new emscripten version fixed it. I'll have another look.

**Comment by grahambates** [comment] 2022-08-05 11:47
Just trying to get to the bottom of this. Proir to v0.8.0, the wasm build of vasm would fail like this when executed with node 18: 
```
$ git checkout v0.7.0
Previous HEAD position was 8eb65c2 v0.8.0
HEAD is now at f6b1bca v0.7.0
$ node server/wasm/vasmm68k_mot ~/example.s
(node:19651) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/batesgw1/m68k-lsp/server/wasm/vasmm68k_mot:143
      throw ex;
      ^

TypeError: Failed to parse URL from /Users/batesgw1/m68k-lsp/server/wasm/vasmm68k_mot.wasm
    at new Request (node:internal/deps/undici/undici:5446:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:6242:25)
    ... 4 lines matching cause stack trace ...
    at Object.<anonymous> (/Users/batesgw1/m68k-lsp/server/wasm/vasmm68k_mot:5043:11)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:387:5)
      at URL.onParseError (node:internal/url:564:9)
      at new URL (node:internal/url:644:5)
      at new Request (node:internal/deps/undici/undici:5444:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:6242:25)
      at Object.fetch (node:internal/deps/undici/undici:7076:20)
      at fetch (node:internal/bootstrap/pre_execution:199:25)
      at instantiateAsync (/Users/batesgw1/m68k-lsp/server/wasm/vasmm68k_mot:1593:14)
      at createWasm (/Users/batesgw1/m68k-lsp/server/wasm/vasmm68k_mot:1630:3)
      at Object.<anonymous> (/Users/batesgw1/m68k-lsp/server/wasm/vasmm68k_mot:5043:11) {
    input: '/Users/batesgw1/m68k-lsp/server/wasm/vasmm68k_mot.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.7.0
```

After the fix this no longer happens and it successfully assembles a source file (the warning at the end is unrelated):

```
$ git checkout v0.8.0
HEAD is now at 8eb65c2 v0.8.0
$ node server/wasm/vasmm68k_mot ~/example.s               
vasm 1.9 (c) in 2002-2022 Volker Barthelmann
vasm M68k/CPU32/ColdFire cpu backend 2.5 (c) 2002-2021 Frank Wille
vasm motorola syntax module 3.15d (c) 2002-2022 Frank Wille
vasm test output module 1.0 (c) 2002 Volker Barthelmann

CODE(acrx2):	          2 bytes
program exited (with status: 0), but EXIT_RUNTIME is not set, so halting execution but not exiting the runtime or preventing further async execution (build with EXIT_RUNTIME=1, if you want a true shutdown)
```

@docbobo do you see something different if you try to reproduce it this way?

**Comment by docbobo** [comment] 2022-08-05 12:10
I've tried the exact same steps are you and I am also seeing the exact same result. Weird.

So I disable the workaround and tried again. Here's what the lsp.log says:

```
[START][2022-08-05 14:06:52] LSP logging initiated
[ERROR][2022-08-05 14:06:52] .../vim/lsp/rpc.lua:420    "rpc"   "m68k-lsp-server"       "stderr"        "(node:612466) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time\n(Use `node --trace-warnings ...` to show where the warning was created)\n"
[ERROR][2022-08-05 14:06:52] .../vim/lsp/rpc.lua:420    "rpc"   "m68k-lsp-server"       "stderr"        "node:internal/deps/undici/undici:5446\n            throw new TypeError(\"Failed to parse URL from \" + input, { cause: err });\n                  ^\n\nTypeError: Failed to parse URL from /usr/lib/node_modules/m68k-lsp-server/node_modules/web-tree-sitter/tree-sitter.wasm\n    at new Request (node:internal/deps/undici/undici:5446:19)\n    at Agent.fetch2 (node:internal/deps/undici/undici:6242:25)\n    ... 4 lines matching cause stack trace ...\n    at new Promise (<anonymous>)\n    at Parser.init (/usr/lib/node_modules/m68k-lsp-server/node_modules/web-tree-sitter/tree-sitter.js:1:332)\n    at Kl (/usr/lib/node_modules/m68k-lsp-server/out/server.js:302:2915)\n    at /usr/lib/node_modules/m68k-lsp-server/out/server.js:302:3197 {\n  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL\n      at new NodeError (node:internal/errors:387:5)\n      at URL.onParseError (node:internal/url:564:9)\n      at new URL (node:internal/url:644:5)\n      at new Request (node:internal/deps/undici/undici:5444:25)\n      at Agent.fetch2 (node:internal/deps/undici/undici:6242:25)\n      at Object.fetch (node:internal/deps/undici/undici:7076:20)\n      at fetch (node:internal/bootstrap/pre_execution:199:25)\n      at /usr/lib/node_modules/m68k-lsp-server/node_modules/web-tree-sitter/tree-sitter.js:1:15192\n      at /usr/lib/node_modules/m68k-lsp-server/node_modules/web-tree-sitter/tree-sitter.js:1:15413\n      at new Promise (<anonymous>) {\n    input: '/usr/lib/node_modules/m68k-lsp-server/node_modules/web-tree-sitter/tree-sitter.wasm',\n    code: 'ERR_INVALID_URL'\n  }\n}\n\nNode.js v18.7.0\n"
``` 

So something must be different when started through that shell script...

**Comment by docbobo** [comment] 2022-08-05 12:45
One thing I just noticed in the stack, not sure if it's relevant: this seems to be complaining about the `tree-sitter.wasm`. I suspect that's not involved in the test scenario above - or is it?

**Comment by grahambates** [comment] 2022-08-05 15:50
Ah ok it looks like the same problem in this file too. This comes from upstream in the tree-sitter package so I'd imagine updating to the latest version should sort it.

**Comment by grahambates** [comment] 2022-08-05 16:01
Looks like that was wishful thinking - there's no fix released upstream as yet:
https://github.com/tree-sitter/tree-sitter/issues/1765

I should be able to build it myself and bundle it. Failing that we could go with the `--no-experimental-fetch` fix, but I didn't really want to break compatibity with older node versions.

**Comment by docbobo** [comment] 2022-08-05 18:35
No worries then - I have a workaround right now. Can we a few days for the real fix ;) 

Thanks!

**Closed as completed** 2022-10-07 17:12 UTC
